[package]
name = "serotonin"
version = "0.3.2"
edition = "2021"

build = "src/build.rs"

[dependencies]
pest = { git = "https://github.com/Alextopher/pest.git", branch = "master" }
pest_derive = "^2.0"
include_dir = "^0.7"
clap = "^3.2" 
colored = "^2.0.0"
bf_instrumentor = { git = "https://github.com/Alextopher/bf_instrumentor", version = "0.1.5" }
either = "^1.7"

[dev-dependencies]
