[package]
name = "serotonin"
version = "0.3.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
build = "src/build.rs"

[dependencies]
pest = { git = "https://github.com/pest-parser/pest.git", branch = "master" }
pest_derive = "^2.0"
include_dir = "0.7.2"
clap = "^3.2" 
colored = "^2.0.0"
bf_instrumentor = { git = "https://github.com/Alextopher/bf_instrumentor", version = "0.1.5" }
either = "1.7.0"
lazy_static = "1.4"

[dev-dependencies]
rayon = "1.5.3"
rand = "0.8.5"