[package]
name = "serotonin-parser"
version = "1.0.0"
edition = "2021"

[dependencies]
colored = "2.1"
logos = "0.13"
snailquote = "0.3.1"
lasso = "0.7"
codespan-reporting = "0.11"
num = "0.4"

[dev-dependencies]
proptest = "1.5"