[package]
name = "serotonin-semantics"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lasso = "0.7"
codespan-reporting = "0.11"
serotonin-parser = { path = "../serotonin-parser" }