[package]
name = "serotonin-frontend"
version = "1.0.0"
edition = "2021"

[dependencies]
serotonin-lexer = { path = "../serotonin-lexer" }
serotonin-parser = { path = "../serotonin-parser" }
serotonin-semantics = { path = "../serotonin-semantics" }
