[package]
name = "serotonin-frontend"
version = "1.0.0"
edition = "2021"

[dependencies]
colored = "2.1"
logos = "0.13"
snailquote = "0.3.1"
lasso = "0.7"
codespan-reporting = "0.11"
num = "0.4"
either = "1.13"
const_fn = "0.4.10"

[dev-dependencies]
proptest = "1.5"
rand = "0.8.5"
