[package]
name = "serotonin-lexer"
version = "0.1.0"
edition = "2021"

[dependencies]
codespan-reporting = "0.11.1"
colored = "2.1.0"
lasso = "0.7.2"
logos = "0.13.0"
num = "0.4.3"
rand = "0.8.5"
snailquote = "0.3.1"

[dev-dependencies]
proptest = "1.5.0"
